/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package br.maua.respondasepuder.telas;

import br.maua.respondasepuder.modelo.Papel;
import br.maua.respondasepuder.modelo.Usuario;
import br.maua.respondasepuder.persistencia.UsuarioDAO;
import javax.swing.JOptionPane;

/**
 *
 * @author Arthur
 */
public class TelaAutenticarUsuario extends javax.swing.JFrame {

    /**
     * Creates new form TelaAutenticarUsuario
     */
    public TelaAutenticarUsuario() {
        super("Responda se puder");
        initComponents();
        setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        emailLoginTextField = new javax.swing.JTextField();
        senhaLoginPasswordField = new javax.swing.JPasswordField();
        entrarButton = new javax.swing.JButton();
        esqueceuSenhaButton = new javax.swing.JButton();
        imageLabel = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        emailLoginTextField.setBackground(new java.awt.Color(0, 176, 185));
        emailLoginTextField.setFont(new java.awt.Font("Arial", 0, 24)); // NOI18N
        emailLoginTextField.setBorder(null);
        emailLoginTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                emailLoginTextFieldActionPerformed(evt);
            }
        });
        getContentPane().add(emailLoginTextField, new org.netbeans.lib.awtextra.AbsoluteConstraints(1220, 330, 310, 80));

        senhaLoginPasswordField.setBackground(new java.awt.Color(0, 176, 185));
        senhaLoginPasswordField.setFont(new java.awt.Font("Arial", 0, 24)); // NOI18N
        senhaLoginPasswordField.setBorder(null);
        getContentPane().add(senhaLoginPasswordField, new org.netbeans.lib.awtextra.AbsoluteConstraints(1220, 490, 310, 70));

        entrarButton.setContentAreaFilled(false);
        entrarButton.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        entrarButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                entrarButtonActionPerformed(evt);
            }
        });
        getContentPane().add(entrarButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(1100, 630, 460, 100));

        esqueceuSenhaButton.setContentAreaFilled(false);
        esqueceuSenhaButton.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        esqueceuSenhaButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                esqueceuSenhaButtonActionPerformed(evt);
            }
        });
        getContentPane().add(esqueceuSenhaButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(1190, 770, 330, 40));

        imageLabel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/Tela autenticar usuário.png"))); // NOI18N
        getContentPane().add(imageLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, -40, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void emailLoginTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_emailLoginTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_emailLoginTextFieldActionPerformed

    private void entrarButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_entrarButtonActionPerformed
        var email = emailLoginTextField.getText();
        var senha = senhaLoginPasswordField.getText();
        var u = Usuario.builder()
                .email(email)
                .senha(senha)
                .build();
        var dao = new UsuarioDAO();
        try {
            if(email.length() > 0 || senha.length() > 0){
                if (dao.autenticarUsuario(u)) {
                    var usuarioCompleto = dao.buscarPorEmail(email);
                    Usuario.setUsuarioLogadoObj(usuarioCompleto);
                    System.out.println(usuarioCompleto);
                    if (Papel.getIdentificador() == 1) {
                        var telaInicio = new TelaDeInicio();
                        telaInicio.setVisible(true);
                        this.dispose();
                    }
                    else if (Papel.getIdentificador() == 2) {
                        var telaAdm = new TelaDeADM();
                        telaAdm.setVisible(true);
                        this.dispose();
                    }
                }
                else{
                    JOptionPane.showMessageDialog(null, "Email ou senha inválidos");
                }
            }
            else{
                JOptionPane.showMessageDialog(null, "Insira email e senha");
            }
        } catch (Exception e) {
            e.printStackTrace();
            //Logger.getLogger(TelaAutenticarUsuario.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_entrarButtonActionPerformed

    private void esqueceuSenhaButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_esqueceuSenhaButtonActionPerformed
        new TelaEsqueciASenha().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_esqueceuSenhaButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TelaAutenticarUsuario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TelaAutenticarUsuario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TelaAutenticarUsuario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TelaAutenticarUsuario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TelaAutenticarUsuario().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField emailLoginTextField;
    private javax.swing.JButton entrarButton;
    private javax.swing.JButton esqueceuSenhaButton;
    private javax.swing.JLabel imageLabel;
    private javax.swing.JPasswordField senhaLoginPasswordField;
    // End of variables declaration//GEN-END:variables
}
