/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package br.maua.respondarsepuder.telas;

/**
 *
 * @author Arthur
 */
public class TelaResultadosPartida extends javax.swing.JFrame {

    /**
     * Creates new form TelaResultadosPartida
     */
    public TelaResultadosPartida() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jogarNovamenteButton = new javax.swing.JButton();
        voltarResultadosButton = new javax.swing.JButton();
        pontuacaoPartidaLabel = new javax.swing.JLabel();
        QuestoesCorretasPartidaLabel = new javax.swing.JLabel();
        imageLabel = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jogarNovamenteButton.setContentAreaFilled(false);
        jogarNovamenteButton.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        getContentPane().add(jogarNovamenteButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 863, 470, 90));

        voltarResultadosButton.setContentAreaFilled(false);
        voltarResultadosButton.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        getContentPane().add(voltarResultadosButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(1070, 863, 480, 90));

        pontuacaoPartidaLabel.setFont(new java.awt.Font("Segoe UI", 1, 48)); // NOI18N
        pontuacaoPartidaLabel.setForeground(new java.awt.Color(255, 255, 255));
        getContentPane().add(pontuacaoPartidaLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(1090, 240, 380, 110));

        QuestoesCorretasPartidaLabel.setFont(new java.awt.Font("Segoe UI", 1, 48)); // NOI18N
        QuestoesCorretasPartidaLabel.setForeground(new java.awt.Color(255, 255, 255));
        getContentPane().add(QuestoesCorretasPartidaLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(1100, 450, 370, 100));

        imageLabel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/Tela resultados partida.png"))); // NOI18N
        getContentPane().add(imageLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, -40, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TelaResultadosPartida.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TelaResultadosPartida.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TelaResultadosPartida.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TelaResultadosPartida.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TelaResultadosPartida().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel QuestoesCorretasPartidaLabel;
    private javax.swing.JLabel imageLabel;
    private javax.swing.JButton jogarNovamenteButton;
    private javax.swing.JLabel pontuacaoPartidaLabel;
    private javax.swing.JButton voltarResultadosButton;
    // End of variables declaration//GEN-END:variables
}
