/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package br.maua.respondasepuder.telas;

import br.maua.respondasepuder.Jogo;
import br.maua.respondasepuder.persistencia.AlunoDAO;
import br.maua.respondasepuder.persistencia.PartidaDAO;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JFrame;

/**
 *
 * @author Arthur
 */
public class TelaConfirmarDesistencia extends javax.swing.JFrame {

    /**
     * Creates new form TelaConfirmarDesistencia
     */
    private Jogo jogo;
    private int numeroQuestaoInt;
    private JFrame telaAnterior;
    public TelaConfirmarDesistencia(Jogo jogo, int numeroQuestaoInt, JFrame telaAnterior){
        this.jogo = jogo;
        this.numeroQuestaoInt = numeroQuestaoInt;
        this.telaAnterior = telaAnterior;
        Transparencia t = new Transparencia();
        t.aplicarTransparencia(this);
        initComponents();
        pontuacaoAtualLabel.setText(String.valueOf(jogo.receberPontuacao(jogo.pergunta - 1, true)));
    }

    private TelaConfirmarDesistencia() {
        throw new UnsupportedOperationException("Not supported yet."); // Generated from nbfs://nbhost/SystemFileSystem/Templates/Classes/Code/GeneratedMethodBody
    }
    AlunoDAO dao = new AlunoDAO();

 

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pontuacaoAtualLabel = new javax.swing.JLabel();
        confirmarDesistenciaButton = new javax.swing.JButton();
        cancelarDesistenciaButton = new javax.swing.JButton();
        imageLabel = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        pontuacaoAtualLabel.setBackground(new java.awt.Color(255, 255, 255));
        pontuacaoAtualLabel.setFont(new java.awt.Font("Arial", 1, 48)); // NOI18N
        pontuacaoAtualLabel.setForeground(new java.awt.Color(255, 255, 255));
        getContentPane().add(pontuacaoAtualLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(1030, 280, 310, 70));

        confirmarDesistenciaButton.setContentAreaFilled(false);
        confirmarDesistenciaButton.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        confirmarDesistenciaButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                confirmarDesistenciaButtonActionPerformed(evt);
            }
        });
        getContentPane().add(confirmarDesistenciaButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 513, 300, 280));

        cancelarDesistenciaButton.setContentAreaFilled(false);
        cancelarDesistenciaButton.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        cancelarDesistenciaButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cancelarDesistenciaButtonActionPerformed(evt);
            }
        });
        getContentPane().add(cancelarDesistenciaButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(1120, 513, 300, 270));

        imageLabel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/Deseja desistir.png"))); // NOI18N
        getContentPane().add(imageLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 70, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void cancelarDesistenciaButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cancelarDesistenciaButtonActionPerformed
        this.dispose();
    }//GEN-LAST:event_cancelarDesistenciaButtonActionPerformed

    private void confirmarDesistenciaButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_confirmarDesistenciaButtonActionPerformed
        telaAnterior.dispose();
        new TelaResultadosPartida(jogo.receberPontuacao(jogo.pergunta - 1, true), this.numeroQuestaoInt - 1).setVisible(true);
        try {
            if (dao.alunoCadastrado()){
                dao.atualizarAluno(this.numeroQuestaoInt - 1, this.numeroQuestaoInt - 1, jogo.receberPontuacao(jogo.pergunta -1, true));
                
            }
            else{
                dao.adicionarAluno(this.numeroQuestaoInt - 1, this.numeroQuestaoInt - 1, jogo.receberPontuacao(jogo.pergunta, false));
            var pdao = new PartidaDAO();
            pdao.adicionarPartida();
            }
        } catch (Exception ex) {
            Logger.getLogger(TelaConfirmarDesistencia.class.getName()).log(Level.SEVERE, null, ex);
        }
        this.dispose();
    }//GEN-LAST:event_confirmarDesistenciaButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TelaConfirmarDesistencia.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TelaConfirmarDesistencia.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TelaConfirmarDesistencia.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TelaConfirmarDesistencia.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TelaConfirmarDesistencia().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton cancelarDesistenciaButton;
    private javax.swing.JButton confirmarDesistenciaButton;
    private javax.swing.JLabel imageLabel;
    private javax.swing.JLabel pontuacaoAtualLabel;
    // End of variables declaration//GEN-END:variables
}
