/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package br.maua.respondasepuder.telas;

import br.maua.respondasepuder.modelo.Usuario;
import br.maua.respondasepuder.persistencia.UsuarioDAO;
import java.awt.event.ActionEvent;
import javax.swing.JOptionPane;

/**
 *
 * @author Arthur
 */
public class TelaAdicionarProfessor extends javax.swing.JFrame {

    /**
     * Creates new form TelaAdicionarProfessor
     */
    public TelaAdicionarProfessor() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
@SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        nomeProfessorTextField = new javax.swing.JTextField();
        emailProfessorTextField = new javax.swing.JTextField();
        senhaProfessorTextField = new javax.swing.JTextField();
        adicionarProfessorButton = new javax.swing.JButton();
        imageLabel = new javax.swing.JLabel();
        voltarAddProfessorButton = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        nomeProfessorTextField.setBackground(new java.awt.Color(0, 176, 185));
        nomeProfessorTextField.setFont(new java.awt.Font("Arial", 0, 24)); // NOI18N
        nomeProfessorTextField.setBorder(null);
        nomeProfessorTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nomeProfessorTextFieldActionPerformed(evt);
            }
        });
        getContentPane().add(nomeProfessorTextField, new org.netbeans.lib.awtextra.AbsoluteConstraints(860, 240, 310, 60));

        emailProfessorTextField.setBackground(new java.awt.Color(0, 176, 185));
        emailProfessorTextField.setFont(new java.awt.Font("Arial", 0, 24)); // NOI18N
        emailProfessorTextField.setBorder(null);
        getContentPane().add(emailProfessorTextField, new org.netbeans.lib.awtextra.AbsoluteConstraints(860, 410, 310, 60));

        senhaProfessorTextField.setBackground(new java.awt.Color(0, 176, 185));
        senhaProfessorTextField.setFont(new java.awt.Font("Arial", 0, 24)); // NOI18N
        senhaProfessorTextField.setBorder(null);
        senhaProfessorTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                senhaProfessorTextFieldActionPerformed(evt);
            }
        });
        getContentPane().add(senhaProfessorTextField, new org.netbeans.lib.awtextra.AbsoluteConstraints(860, 560, 310, 60));

        adicionarProfessorButton.setContentAreaFilled(false);
        adicionarProfessorButton.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        adicionarProfessorButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                adicionarProfessorButtonActionPerformed(evt);
            }
        });
        getContentPane().add(adicionarProfessorButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(730, 720, 480, 100));

        imageLabel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/Tela adicionar professor.png"))); // NOI18N
        getContentPane().add(imageLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, -40, -1, -1));

        voltarAddProfessorButton.setText("jButton1");
        voltarAddProfessorButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                voltarAddProfessorButtonActionPerformed(evt);
            }
        });
        getContentPane().add(voltarAddProfessorButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 10, 150, 150));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void senhaProfessorTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_senhaProfessorTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_senhaProfessorTextFieldActionPerformed

    private void nomeProfessorTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nomeProfessorTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_nomeProfessorTextFieldActionPerformed

    private void adicionarProfessorButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_adicionarProfessorButtonActionPerformed
        var nome = nomeProfessorTextField.getText();
        var email = emailProfessorTextField.getText();
        var senha = senhaProfessorTextField.getText();
        var usuario = Usuario.builder()
                .nome(nome)
                .email(email)
                .senha(senha)
                .build();
        var dao = new UsuarioDAO();
        try {
            dao.adicionarUsuario(usuario, true);
            JOptionPane.showMessageDialog(null, "Professor adicionado com sucesso!");
        }
        catch (Exception ex) {
            JOptionPane.showMessageDialog(
                null, "Erro ao adicionar professor:" + ex.getMessage()
            );
        }
    }//GEN-LAST:event_adicionarProfessorButtonActionPerformed

    private void voltarAddProfessorButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_voltarAddProfessorButtonActionPerformed
        var telaAdm = new TelaDeADM();
        telaAdm.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_voltarAddProfessorButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TelaAdicionarProfessor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TelaAdicionarProfessor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TelaAdicionarProfessor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TelaAdicionarProfessor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TelaAdicionarProfessor().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton adicionarProfessorButton;
    private javax.swing.JTextField emailProfessorTextField;
    private javax.swing.JLabel imageLabel;
    private javax.swing.JTextField nomeProfessorTextField;
    private javax.swing.JTextField senhaProfessorTextField;
    private javax.swing.JButton voltarAddProfessorButton;
    // End of variables declaration//GEN-END:variables
}
