/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package br.maua.respondasepuder.telas;

import br.maua.respondasepuder.modelo.Alternativa;
import br.maua.respondasepuder.modelo.Questao;
import br.maua.respondasepuder.persistencia.AlternativaDAO;
import java.util.*;

/**
 *
 * @author Arthur
 */
public class TelaPergunta extends javax.swing.JFrame {
    private Questao questao;
    public void montarTela(Questao questao) {
        AlternativaDAO dao = new AlternativaDAO();
        List<Alternativa> listaAlternativaConsulta;
        try {
            enunciadoPerguntaLabel.setText(questao.getEnunciado());
            listaAlternativaConsulta = (ArrayList<Alternativa>) dao.consultarAlternativa(questao);
            String alternativaA = listaAlternativaConsulta.get(0).getTexto();
            alternativaALabel.setText(alternativaA);
            String alternativaB = listaAlternativaConsulta.get(1).getTexto();
            alternativaBLabel.setText(alternativaB);
            String alternativaC = listaAlternativaConsulta.get(2).getTexto();
            alternativaCLabel.setText(alternativaC);
            String alternativaD = listaAlternativaConsulta.get(3).getTexto();
            alternativaDLabel.setText(alternativaD);
            String alternativaE = listaAlternativaConsulta.get(4).getTexto();
            alternativaELabel.setText(alternativaE);
        } catch (Exception exception) {
        }
    }
    /**
     * Creates new form TelaPergunta
     */
    public TelaPergunta() {
        initComponents();
        montarTela(questao);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        numeroPerguntaLabel = new javax.swing.JLabel();
        alternativaALabel = new javax.swing.JLabel();
        alternativaAButton = new javax.swing.JButton();
        alternativaBLabel = new javax.swing.JLabel();
        alternativaBButton = new javax.swing.JButton();
        alternativaCLabel = new javax.swing.JLabel();
        alternativaCButton = new javax.swing.JButton();
        alternativaDLabel = new javax.swing.JLabel();
        alternativaDButton = new javax.swing.JButton();
        alternativaELabel = new javax.swing.JLabel();
        alternativaEButton = new javax.swing.JButton();
        eliminarDuasButton = new javax.swing.JButton();
        escudoButton = new javax.swing.JButton();
        pularQuestaoButton = new javax.swing.JButton();
        ativarMusicaButton = new javax.swing.JButton();
        pontuacaoAcumuladaLabel = new javax.swing.JLabel();
        pontuacaoQuestaoLabel = new javax.swing.JLabel();
        enunciadoPerguntaLabel = new javax.swing.JLabel();
        pararJogarButton = new javax.swing.JButton();
        imageLabel = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        numeroPerguntaLabel.setFont(new java.awt.Font("Arial", 0, 48)); // NOI18N
        getContentPane().add(numeroPerguntaLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(1100, 10, -1, 50));

        alternativaALabel.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        alternativaALabel.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        getContentPane().add(alternativaALabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 270, 740, 40));

        alternativaAButton.setBackground(new java.awt.Color(179, 73, 12));
        alternativaAButton.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        getContentPane().add(alternativaAButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 260, 760, 60));

        alternativaBLabel.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        alternativaBLabel.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        getContentPane().add(alternativaBLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 370, 740, 40));

        alternativaBButton.setBackground(new java.awt.Color(179, 73, 12));
        alternativaBButton.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        getContentPane().add(alternativaBButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 360, 760, 60));

        alternativaCLabel.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        alternativaCLabel.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        getContentPane().add(alternativaCLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 460, 740, 40));

        alternativaCButton.setBackground(new java.awt.Color(179, 73, 12));
        alternativaCButton.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        alternativaCButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                alternativaCButtonActionPerformed(evt);
            }
        });
        getContentPane().add(alternativaCButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 450, 760, 60));

        alternativaDLabel.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        alternativaDLabel.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        getContentPane().add(alternativaDLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 560, 740, 40));

        alternativaDButton.setBackground(new java.awt.Color(179, 73, 12));
        alternativaDButton.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        getContentPane().add(alternativaDButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 550, 760, 60));

        alternativaELabel.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        alternativaELabel.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        getContentPane().add(alternativaELabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 660, 740, 40));

        alternativaEButton.setBackground(new java.awt.Color(179, 73, 12));
        alternativaEButton.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        getContentPane().add(alternativaEButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 650, 760, 60));

        eliminarDuasButton.setContentAreaFilled(false);
        eliminarDuasButton.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        getContentPane().add(eliminarDuasButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 450, 130, 110));

        escudoButton.setContentAreaFilled(false);
        escudoButton.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        getContentPane().add(escudoButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 610, 130, 110));

        pularQuestaoButton.setContentAreaFilled(false);
        pularQuestaoButton.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        pularQuestaoButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pularQuestaoButtonActionPerformed(evt);
            }
        });
        getContentPane().add(pularQuestaoButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 280, 130, 110));

        ativarMusicaButton.setContentAreaFilled(false);
        ativarMusicaButton.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        getContentPane().add(ativarMusicaButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 890, 130, 110));

        pontuacaoAcumuladaLabel.setFont(new java.awt.Font("Segoe UI", 0, 36)); // NOI18N
        getContentPane().add(pontuacaoAcumuladaLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 900, 250, 40));

        pontuacaoQuestaoLabel.setFont(new java.awt.Font("Segoe UI", 0, 36)); // NOI18N
        getContentPane().add(pontuacaoQuestaoLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(1350, 900, 310, 40));
        getContentPane().add(enunciadoPerguntaLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(1110, 190, 710, 560));

        pararJogarButton.setContentAreaFilled(false);
        pararJogarButton.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        getContentPane().add(pararJogarButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(1760, 10, 110, 110));

        imageLabel.setBackground(new java.awt.Color(255, 106, 19));
        imageLabel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/Tela perguntas.png"))); // NOI18N
        getContentPane().add(imageLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(-10, -40, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void alternativaCButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_alternativaCButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_alternativaCButtonActionPerformed

    private void pularQuestaoButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pularQuestaoButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_pularQuestaoButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TelaPergunta.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TelaPergunta.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TelaPergunta.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TelaPergunta.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TelaPergunta().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton alternativaAButton;
    private javax.swing.JLabel alternativaALabel;
    private javax.swing.JButton alternativaBButton;
    private javax.swing.JLabel alternativaBLabel;
    private javax.swing.JButton alternativaCButton;
    private javax.swing.JLabel alternativaCLabel;
    private javax.swing.JButton alternativaDButton;
    private javax.swing.JLabel alternativaDLabel;
    private javax.swing.JButton alternativaEButton;
    private javax.swing.JLabel alternativaELabel;
    private javax.swing.JButton ativarMusicaButton;
    private javax.swing.JButton eliminarDuasButton;
    private javax.swing.JLabel enunciadoPerguntaLabel;
    private javax.swing.JButton escudoButton;
    private javax.swing.JLabel imageLabel;
    private javax.swing.JLabel numeroPerguntaLabel;
    private javax.swing.JButton pararJogarButton;
    private javax.swing.JLabel pontuacaoAcumuladaLabel;
    private javax.swing.JLabel pontuacaoQuestaoLabel;
    private javax.swing.JButton pularQuestaoButton;
    // End of variables declaration//GEN-END:variables
}
