/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package br.maua.respondasepuder.telas;


/**
 *
 * @author Arthur
 */
public class TelaPontuacaoAluno extends javax.swing.JFrame {

    
    /**
     * Creates new form TelaPontuacaoAluno
     */
    public TelaPontuacaoAluno() {
        initComponents();
    }
    

    
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        questoesCorretasTotalLabel = new javax.swing.JLabel();
        totalQuestoesLabel = new javax.swing.JLabel();
        pontuacaoAlunoLabel = new javax.swing.JLabel();
        voltarPontuacaoButton = new javax.swing.JButton();
        imageLabel = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        questoesCorretasTotalLabel.setFont(new java.awt.Font("Segoe UI", 1, 48)); // NOI18N
        questoesCorretasTotalLabel.setForeground(new java.awt.Color(255, 255, 255));
        getContentPane().add(questoesCorretasTotalLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(900, 500, 390, 80));

        totalQuestoesLabel.setFont(new java.awt.Font("Segoe UI", 1, 48)); // NOI18N
        totalQuestoesLabel.setForeground(new java.awt.Color(255, 255, 255));
        getContentPane().add(totalQuestoesLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(820, 680, 390, 80));

        pontuacaoAlunoLabel.setFont(new java.awt.Font("Segoe UI", 1, 48)); // NOI18N
        pontuacaoAlunoLabel.setForeground(new java.awt.Color(255, 255, 255));
        getContentPane().add(pontuacaoAlunoLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(710, 310, 390, 80));

        voltarPontuacaoButton.setContentAreaFilled(false);
        voltarPontuacaoButton.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        voltarPontuacaoButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                voltarPontuacaoButtonActionPerformed(evt);
            }
        });
        getContentPane().add(voltarPontuacaoButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 50, 130, 120));

        imageLabel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/Tela pontuação aluno.png"))); // NOI18N
        getContentPane().add(imageLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, -40, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void voltarPontuacaoButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_voltarPontuacaoButtonActionPerformed
        new TelaDeInicio().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_voltarPontuacaoButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TelaPontuacaoAluno.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TelaPontuacaoAluno.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TelaPontuacaoAluno.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TelaPontuacaoAluno.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TelaPontuacaoAluno().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel imageLabel;
    private javax.swing.JLabel pontuacaoAlunoLabel;
    private javax.swing.JLabel questoesCorretasTotalLabel;
    private javax.swing.JLabel totalQuestoesLabel;
    private javax.swing.JButton voltarPontuacaoButton;
    // End of variables declaration//GEN-END:variables
}
