/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package br.maua.respondasepuder.telas;

import br.maua.respondasepuder.modelo.Alternativa;
import br.maua.respondasepuder.modelo.Questao;
import br.maua.respondasepuder.modelo.QuestaoAlternativa;
import br.maua.respondasepuder.persistencia.QuestaoDAO;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

/**
 *
 * @author Arthur
 */
public class TelaAdicionarQuestoes extends javax.swing.JFrame {
    // Cria a variável enunciado
    private String enunciado;
    // Cria as variáveis alternativas
    private String alternativa1;
    private String alternativa2;
    private String alternativa3;
    private String alternativa4;
    private String alternativa5;
    // Cria as variáveis booleanas de alternativas corretas
    private boolean alternativa1EhCorreta;
    private boolean alternativa2EhCorreta;
    private boolean alternativa3EhCorreta;
    private boolean alternativa4EhCorreta;
    private boolean alternativa5EhCorreta;
    // Cria a variável matéria
    private String materia;
    // Cria a variável nível
    private String nivel;
    /**
     * Creates new form TelaAdicionarQuestoes
     */
    public TelaAdicionarQuestoes() {
        super("Responda Se Puder");
        initComponents();
        setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        enunciadoTextField = new javax.swing.JTextField();
        alternativa1TextField = new javax.swing.JTextField();
        alternativa2TextField = new javax.swing.JTextField();
        alternativa3TextField = new javax.swing.JTextField();
        alternativa4TextField = new javax.swing.JTextField();
        alternativa5TextField = new javax.swing.JTextField();
        materiaComboBox = new javax.swing.JComboBox<>();
        questaoDificilButton = new javax.swing.JButton();
        questaoMedioButton = new javax.swing.JButton();
        questaoFacilButton = new javax.swing.JButton();
        adicionarQuestaoButton = new javax.swing.JButton();
        voltarConsultarQuestoesButton = new javax.swing.JButton();
        alternativa1RadioButton = new javax.swing.JRadioButton();
        alternativa2RadioButton = new javax.swing.JRadioButton();
        alternativa5RadioButton = new javax.swing.JRadioButton();
        alternativa3RadioButton = new javax.swing.JRadioButton();
        alternativa4RadioButton = new javax.swing.JRadioButton();
        imageLabel = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        enunciadoTextField.setBackground(new java.awt.Color(0, 176, 185));
        enunciadoTextField.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        enunciadoTextField.setBorder(null);
        getContentPane().add(enunciadoTextField, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 122, 1100, 100));

        alternativa1TextField.setBackground(new java.awt.Color(0, 176, 185));
        alternativa1TextField.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        alternativa1TextField.setBorder(null);
        getContentPane().add(alternativa1TextField, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 330, 1080, 40));

        alternativa2TextField.setBackground(new java.awt.Color(0, 176, 185));
        alternativa2TextField.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        alternativa2TextField.setBorder(null);
        getContentPane().add(alternativa2TextField, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 420, 1080, 40));

        alternativa3TextField.setBackground(new java.awt.Color(0, 176, 185));
        alternativa3TextField.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        alternativa3TextField.setBorder(null);
        getContentPane().add(alternativa3TextField, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 520, 1080, 40));

        alternativa4TextField.setBackground(new java.awt.Color(0, 176, 185));
        alternativa4TextField.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        alternativa4TextField.setBorder(null);
        getContentPane().add(alternativa4TextField, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 610, 1080, 40));

        alternativa5TextField.setBackground(new java.awt.Color(0, 176, 185));
        alternativa5TextField.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        alternativa5TextField.setBorder(null);
        getContentPane().add(alternativa5TextField, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 700, 1080, 40));

        materiaComboBox.setBackground(new java.awt.Color(0, 176, 185));
        materiaComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Matemática", "Português", "História", "Geografia" }));
        materiaComboBox.setBorder(null);
        getContentPane().add(materiaComboBox, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 850, 430, 50));

        questaoDificilButton.setContentAreaFilled(false);
        questaoDificilButton.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        questaoDificilButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                questaoDificilButtonActionPerformed(evt);
            }
        });
        getContentPane().add(questaoDificilButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(1420, 860, 230, 40));

        questaoMedioButton.setContentAreaFilled(false);
        questaoMedioButton.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        questaoMedioButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                questaoMedioButtonActionPerformed(evt);
            }
        });
        getContentPane().add(questaoMedioButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(1170, 860, 220, 40));

        questaoFacilButton.setContentAreaFilled(false);
        questaoFacilButton.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        questaoFacilButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                questaoFacilButtonActionPerformed(evt);
            }
        });
        getContentPane().add(questaoFacilButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(920, 860, 230, 40));

        adicionarQuestaoButton.setContentAreaFilled(false);
        adicionarQuestaoButton.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        adicionarQuestaoButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                adicionarQuestaoButtonActionPerformed(evt);
            }
        });
        getContentPane().add(adicionarQuestaoButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(740, 940, 480, 100));

        voltarConsultarQuestoesButton.setContentAreaFilled(false);
        voltarConsultarQuestoesButton.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        getContentPane().add(voltarConsultarQuestoesButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 90, 110, 110));

        buttonGroup1.add(alternativa1RadioButton);
        alternativa1RadioButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                alternativa1RadioButtonActionPerformed(evt);
            }
        });
        getContentPane().add(alternativa1RadioButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 300, 30, 100));

        buttonGroup1.add(alternativa2RadioButton);
        alternativa2RadioButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                alternativa2RadioButtonActionPerformed(evt);
            }
        });
        getContentPane().add(alternativa2RadioButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 390, 30, 90));

        buttonGroup1.add(alternativa5RadioButton);
        alternativa5RadioButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                alternativa5RadioButtonActionPerformed(evt);
            }
        });
        getContentPane().add(alternativa5RadioButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 690, 30, 30));

        buttonGroup1.add(alternativa3RadioButton);
        alternativa3RadioButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                alternativa3RadioButtonActionPerformed(evt);
            }
        });
        getContentPane().add(alternativa3RadioButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 510, 30, 30));

        buttonGroup1.add(alternativa4RadioButton);
        alternativa4RadioButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                alternativa4RadioButtonActionPerformed(evt);
            }
        });
        getContentPane().add(alternativa4RadioButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 600, 30, 30));

        imageLabel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/Tela AddPerguntas.png"))); // NOI18N
        getContentPane().add(imageLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void alternativa2RadioButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_alternativa2RadioButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_alternativa2RadioButtonActionPerformed

    private void alternativa5RadioButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_alternativa5RadioButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_alternativa5RadioButtonActionPerformed

    private void alternativa1RadioButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_alternativa1RadioButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_alternativa1RadioButtonActionPerformed

    private void alternativa3RadioButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_alternativa3RadioButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_alternativa3RadioButtonActionPerformed

    private void alternativa4RadioButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_alternativa4RadioButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_alternativa4RadioButtonActionPerformed

    private void adicionarQuestaoButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_adicionarQuestaoButtonActionPerformed
        // Pegar o texto do enunciado
        this.enunciado = enunciadoTextField.getText();
        // Pegar os textos das alternativas
        this.alternativa1 = alternativa1TextField.getText();
        this.alternativa2 = alternativa2TextField.getText();
        this.alternativa3 = alternativa3TextField.getText();
        this.alternativa4 = alternativa4TextField.getText();
        this.alternativa5 = alternativa5TextField.getText();
        // Pegar a informação se cada alternativa está correta
        this.alternativa1EhCorreta = alternativa1RadioButton.isSelected();
        this.alternativa2EhCorreta = alternativa2RadioButton.isSelected();
        this.alternativa3EhCorreta = alternativa3RadioButton.isSelected();
        this.alternativa4EhCorreta = alternativa4RadioButton.isSelected();
        this.alternativa5EhCorreta = alternativa5RadioButton.isSelected();
        // Pegar a matéria
        this.materia = (String) materiaComboBox.getSelectedItem();
        // Modelo de objetos para cadastro na base
        try{
            var questao = Questao.builder()
                .enunciado(enunciado)
                .materia(materia)
                .nivel(nivel)
                .build();
            var qa1 = new QuestaoAlternativa(
                questao,
                Alternativa.builder()
                    .texto (alternativa1)
                    .build(),
                alternativa1EhCorreta
            );
            var qa2 = new QuestaoAlternativa(
                questao,
                Alternativa.builder()
                    .texto (alternativa2)
                    .build(),
                alternativa2EhCorreta
            );
            var qa3 = new QuestaoAlternativa(
                questao,
                Alternativa.builder()
                    .texto (alternativa3)
                    .build(),
                alternativa3EhCorreta
            );
            var qa4 = new QuestaoAlternativa(
                questao,
                Alternativa.builder()
                    .texto (alternativa4)
                    .build(),
                alternativa4EhCorreta
            );
            var qa5 = new QuestaoAlternativa(
                questao,
                Alternativa.builder()
                    .texto (alternativa5)
                    .build(),
                alternativa5EhCorreta
            );
            questao.getAlternativas().add(qa1);
            questao.getAlternativas().add(qa2);
            questao.getAlternativas().add(qa3);
            questao.getAlternativas().add(qa4);
            questao.getAlternativas().add(qa5);
        
            var queDAO = new QuestaoDAO();
            queDAO.adicionarQuestao(questao);
        }catch(Exception ex){
            JOptionPane.showMessageDialog(null, "Erro ao adicionar questão: " + ex.getMessage());
        }
    }//GEN-LAST:event_adicionarQuestaoButtonActionPerformed
    private void questaoFacilButtonActionPerformed(java.awt.event.ActionEvent evt) {
        this.nivel = "Fácil";
    } 
    private void questaoMedioButtonActionPerformed(java.awt.event.ActionEvent evt) {
        this.nivel = "Médio";
    }
    private void questaoDificilButtonActionPerformed(java.awt.event.ActionEvent evt) {
        this.nivel = "Difícil";
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TelaAdicionarQuestoes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TelaAdicionarQuestoes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TelaAdicionarQuestoes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TelaAdicionarQuestoes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TelaAdicionarQuestoes().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton adicionarQuestaoButton;
    private javax.swing.JRadioButton alternativa1RadioButton;
    private javax.swing.JTextField alternativa1TextField;
    private javax.swing.JRadioButton alternativa2RadioButton;
    private javax.swing.JTextField alternativa2TextField;
    private javax.swing.JRadioButton alternativa3RadioButton;
    private javax.swing.JTextField alternativa3TextField;
    private javax.swing.JRadioButton alternativa4RadioButton;
    private javax.swing.JTextField alternativa4TextField;
    private javax.swing.JRadioButton alternativa5RadioButton;
    private javax.swing.JTextField alternativa5TextField;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JTextField enunciadoTextField;
    private javax.swing.JLabel imageLabel;
    private javax.swing.JComboBox<String> materiaComboBox;
    private javax.swing.JButton questaoDificilButton;
    private javax.swing.JButton questaoFacilButton;
    private javax.swing.JButton questaoMedioButton;
    private javax.swing.JButton voltarConsultarQuestoesButton;
    // End of variables declaration//GEN-END:variables
}
