/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package br.maua.respondasepuder.telas;

import br.maua.respondasepuder.modelo.Materia;
import br.maua.respondasepuder.persistencia.MateriaDAO;
import java.util.ArrayList;
import java.util.List;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JOptionPane;

/**
 *
 * @author Arthur
 */
public class TelaOpcoes extends javax.swing.JFrame {
    private void obterMateriaComboBox() {
        try {
            var dao = new MateriaDAO();
            var materias = dao.obterMateria();
            selecionarMateriaComboBox.setModel(
                    new DefaultComboBoxModel<Materia>(materias.toArray(new Materia[]{}))
            );
        }
        catch (Exception e) {
            e.printStackTrace();
            JOptionPane.showMessageDialog(null, "Lista de matérias");
        }
    }
    public interface MateriaSelectionListener {

        void onMateriaSelected(String materia);
    }

        private List<MateriaSelectionListener> listeners = new ArrayList<>();

        public void addMateriaSelectionListener(MateriaSelectionListener listener) {
            listeners.add(listener);
        }
        
        private void notificarMateriaAlterada() {
            String materiaSelecionada = opcaoMateriaSelecionada();
            for (MateriaSelectionListener listener : listeners) {
                listener.onMateriaSelected(materiaSelecionada);
            }
        }

    
    public String opcaoMateriaSelecionada(){
        Materia m = (Materia) selecionarMateriaComboBox.getSelectedItem();
        return m.getNome();
    }

    /**
     * Creates new form TelaOpcoes
     */
    public TelaOpcoes() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        selecionarMateriaComboBox = new javax.swing.JComboBox<Materia>();
        selecionarDificuldadeComboBox1 = new javax.swing.JComboBox<>();
        voltarOpcoesButton = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        selecionarMateriaComboBox.setBackground(new java.awt.Color(0, 176, 185));
        selecionarMateriaComboBox.setBorder(null);
        selecionarMateriaComboBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                selecionarMateriaComboBoxActionPerformed(evt);
            }
        });
        getContentPane().add(selecionarMateriaComboBox, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 340, 1230, 60));

        selecionarDificuldadeComboBox1.setBackground(new java.awt.Color(0, 176, 185));
        selecionarDificuldadeComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Todas", "Fácil", "Médio", "Difícil" }));
        selecionarDificuldadeComboBox1.setBorder(null);
        getContentPane().add(selecionarDificuldadeComboBox1, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 590, 1230, 60));

        voltarOpcoesButton.setContentAreaFilled(false);
        voltarOpcoesButton.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        voltarOpcoesButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                voltarOpcoesButtonActionPerformed(evt);
            }
        });
        getContentPane().add(voltarOpcoesButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 50, 120, 120));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/Tela opcoes.png"))); // NOI18N
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, -40, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void voltarOpcoesButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_voltarOpcoesButtonActionPerformed
        this.dispose();
    }//GEN-LAST:event_voltarOpcoesButtonActionPerformed

    private void selecionarMateriaComboBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_selecionarMateriaComboBoxActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_selecionarMateriaComboBoxActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TelaOpcoes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TelaOpcoes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TelaOpcoes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TelaOpcoes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TelaOpcoes().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JComboBox<String> selecionarDificuldadeComboBox1;
    private javax.swing.JComboBox<Materia> selecionarMateriaComboBox;
    private javax.swing.JButton voltarOpcoesButton;
    // End of variables declaration//GEN-END:variables
}
