/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package br.maua.respondasepuder.telas;

import javax.swing.ListSelectionModel;
import javax.swing.table.DefaultTableModel;
/**
 *
 * @author Arthur
 */
public class TelaRanque extends javax.swing.JFrame {

    /**
     * Creates new form TelaRanque
     */
    private DefaultTableModel modeloTabela;
    public TelaRanque() {
        super("Responda se puder");
        initComponents();
        setLocationRelativeTo(null);    }

    private void configurarTabela() {
        //Define os nomes das colunas da tabela
        String[] colunas = {"Nome", "Maior potuação"};
        //Constrói um objeto e passa como argumentos as colunas e o número de linhas.
        modeloTabela = new DefaultTableModel(colunas, 0);
        //Define o modelo da tabela "ranqueTable" como "modeloTabela".
        ranqueTable.setModel(modeloTabela);
        //Define o tamanho das linhas para 25 pixels.
        ranqueTable.setRowHeight(25);
        //Permite a seleção de uma linha por vez.
        ranqueTable.setSelectionMode(ListSelectionModel.SINGLE_SELECTION);
        //Não permite que o usuário reordene as colunas da tabela.
        ranqueTable.getTableHeader().setReorderingAllowed(false);
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        ranqueTable = new javax.swing.JTable();
        voltarRanqueButton = new javax.swing.JButton();
        imageLabel = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        ranqueTable.setBackground(new java.awt.Color(217, 217, 217));
        ranqueTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Nome", "Pontuação", "Questões Respondidas", "Questões Corretas"
            }
        ));
        jScrollPane1.setViewportView(ranqueTable);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 160, 1460, 760));

        voltarRanqueButton.setContentAreaFilled(false);
        voltarRanqueButton.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        voltarRanqueButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                voltarRanqueButtonActionPerformed(evt);
            }
        });
        getContentPane().add(voltarRanqueButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 50, 120, 110));

        imageLabel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/Tela de ver ranque.png"))); // NOI18N
        getContentPane().add(imageLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(-10, -40, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void voltarRanqueButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_voltarRanqueButtonActionPerformed
        new TelaDeADM().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_voltarRanqueButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TelaRanque.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TelaRanque.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TelaRanque.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TelaRanque.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TelaRanque().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel imageLabel;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable ranqueTable;
    private javax.swing.JButton voltarRanqueButton;
    // End of variables declaration//GEN-END:variables
}
