/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package br.maua.respondasepuder.telas;

import br.maua.respondasepuder.Jogo;

/**
 *
 * @author Arthur
 */
public class TelaResultadosPartida extends javax.swing.JFrame {
    public int pontuacaoAcumulada;
    public int numeroQuestaoInt;
    /**
     * Creates new form TelaResultadosPartida
     */
    public TelaResultadosPartida(int pontuacaoAcumulada, int numeroQuestaoInt) {
        this.pontuacaoAcumulada = pontuacaoAcumulada;
        this.numeroQuestaoInt = numeroQuestaoInt;
        initComponents();
        montarTela();
    }
    
    public void montarTela() {
        pontuacaoPartidaLabel.setText(String.valueOf(pontuacaoAcumulada));
        questoesCorretasPartidaLabel.setText(String.valueOf(numeroQuestaoInt));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jogarNovamenteButton = new javax.swing.JButton();
        voltarResultadosButton = new javax.swing.JButton();
        pontuacaoPartidaLabel = new javax.swing.JLabel();
        questoesCorretasPartidaLabel = new javax.swing.JLabel();
        imageLabel = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jogarNovamenteButton.setContentAreaFilled(false);
        jogarNovamenteButton.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jogarNovamenteButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jogarNovamenteButtonActionPerformed(evt);
            }
        });
        getContentPane().add(jogarNovamenteButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 863, 470, 90));

        voltarResultadosButton.setContentAreaFilled(false);
        voltarResultadosButton.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        voltarResultadosButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                voltarResultadosButtonActionPerformed(evt);
            }
        });
        getContentPane().add(voltarResultadosButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(1070, 863, 480, 90));

        pontuacaoPartidaLabel.setFont(new java.awt.Font("Segoe UI", 1, 48)); // NOI18N
        pontuacaoPartidaLabel.setForeground(new java.awt.Color(255, 255, 255));
        getContentPane().add(pontuacaoPartidaLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(1090, 240, 380, 110));

        questoesCorretasPartidaLabel.setFont(new java.awt.Font("Segoe UI", 1, 48)); // NOI18N
        questoesCorretasPartidaLabel.setForeground(new java.awt.Color(255, 255, 255));
        getContentPane().add(questoesCorretasPartidaLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(1100, 450, 370, 100));

        imageLabel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/Tela resultados partida.png"))); // NOI18N
        getContentPane().add(imageLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, -40, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jogarNovamenteButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jogarNovamenteButtonActionPerformed
        try {
            Jogo jogo = new Jogo();
            jogo.novaPartida();
            var questaoAleatoria = jogo.randomizarPergunta();

            new TelaPergunta(jogo, questaoAleatoria).setVisible(true);
            this.dispose();
        } catch (Exception e) {
            e.printStackTrace();
        }
    }//GEN-LAST:event_jogarNovamenteButtonActionPerformed

    private void voltarResultadosButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_voltarResultadosButtonActionPerformed
        new TelaDeInicio().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_voltarResultadosButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TelaResultadosPartida.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TelaResultadosPartida.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TelaResultadosPartida.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TelaResultadosPartida.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                var pontuacaoAcumulada = 0;
                var numeroQuestaoInt = 0;
                new TelaResultadosPartida(pontuacaoAcumulada, numeroQuestaoInt).setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel imageLabel;
    private javax.swing.JButton jogarNovamenteButton;
    private javax.swing.JLabel pontuacaoPartidaLabel;
    private javax.swing.JLabel questoesCorretasPartidaLabel;
    private javax.swing.JButton voltarResultadosButton;
    // End of variables declaration//GEN-END:variables
}
