/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package br.maua.respondarsepuder.telas;

/**
 *
 * @author Arthur
 */
public class TelaAdicionarQuestoes extends javax.swing.JFrame {

    /**
     * Creates new form TelaAdicionarQuestoes
     */
    public TelaAdicionarQuestoes() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        perguntaTextField5 = new javax.swing.JTextField();
        alternativa1TextField = new javax.swing.JTextField();
        alternativa2TextField1 = new javax.swing.JTextField();
        alternativa3TextField2 = new javax.swing.JTextField();
        alterntiva4TextField3 = new javax.swing.JTextField();
        alternativa5TextField4 = new javax.swing.JTextField();
        materiaComboBox = new javax.swing.JComboBox<>();
        questaoDificilButton = new javax.swing.JButton();
        questaoMedioButton1 = new javax.swing.JButton();
        questaoFacilButton2 = new javax.swing.JButton();
        adicionarQuestaoButton = new javax.swing.JButton();
        voltarConsultarQuestoesButton = new javax.swing.JButton();
        alternativa1RadioButton = new javax.swing.JRadioButton();
        alternativa2RadioButton = new javax.swing.JRadioButton();
        alternativa5RadioButton = new javax.swing.JRadioButton();
        alternativa3RadioButton = new javax.swing.JRadioButton();
        alternativa4RadioButton = new javax.swing.JRadioButton();
        imageLabel = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        perguntaTextField5.setBackground(new java.awt.Color(0, 176, 185));
        perguntaTextField5.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        perguntaTextField5.setBorder(null);
        getContentPane().add(perguntaTextField5, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 92, 1100, 100));

        alternativa1TextField.setBackground(new java.awt.Color(0, 176, 185));
        alternativa1TextField.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        alternativa1TextField.setBorder(null);
        getContentPane().add(alternativa1TextField, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 300, 1080, 40));

        alternativa2TextField1.setBackground(new java.awt.Color(0, 176, 185));
        alternativa2TextField1.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        alternativa2TextField1.setBorder(null);
        getContentPane().add(alternativa2TextField1, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 390, 1080, 40));

        alternativa3TextField2.setBackground(new java.awt.Color(0, 176, 185));
        alternativa3TextField2.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        alternativa3TextField2.setBorder(null);
        getContentPane().add(alternativa3TextField2, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 490, 1080, 40));

        alterntiva4TextField3.setBackground(new java.awt.Color(0, 176, 185));
        alterntiva4TextField3.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        alterntiva4TextField3.setBorder(null);
        getContentPane().add(alterntiva4TextField3, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 580, 1080, 40));

        alternativa5TextField4.setBackground(new java.awt.Color(0, 176, 185));
        alternativa5TextField4.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        alternativa5TextField4.setBorder(null);
        getContentPane().add(alternativa5TextField4, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 670, 1080, 40));

        materiaComboBox.setBackground(new java.awt.Color(0, 176, 185));
        materiaComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Matemática", "Português", "História", "Geografia" }));
        materiaComboBox.setBorder(null);
        getContentPane().add(materiaComboBox, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 820, 430, 50));

        questaoDificilButton.setContentAreaFilled(false);
        questaoDificilButton.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        getContentPane().add(questaoDificilButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(1420, 830, 230, 40));

        questaoMedioButton1.setContentAreaFilled(false);
        questaoMedioButton1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        getContentPane().add(questaoMedioButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(1170, 830, 220, 40));

        questaoFacilButton2.setContentAreaFilled(false);
        questaoFacilButton2.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        getContentPane().add(questaoFacilButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(920, 830, 230, 40));

        adicionarQuestaoButton.setContentAreaFilled(false);
        adicionarQuestaoButton.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        getContentPane().add(adicionarQuestaoButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(740, 910, 480, 100));

        voltarConsultarQuestoesButton.setContentAreaFilled(false);
        voltarConsultarQuestoesButton.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        getContentPane().add(voltarConsultarQuestoesButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 60, 110, 110));

        buttonGroup1.add(alternativa1RadioButton);
        alternativa1RadioButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                alternativa1RadioButtonActionPerformed(evt);
            }
        });
        getContentPane().add(alternativa1RadioButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 270, 30, 100));

        buttonGroup1.add(alternativa2RadioButton);
        alternativa2RadioButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                alternativa2RadioButtonActionPerformed(evt);
            }
        });
        getContentPane().add(alternativa2RadioButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 360, 30, 90));

        buttonGroup1.add(alternativa5RadioButton);
        alternativa5RadioButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                alternativa5RadioButtonActionPerformed(evt);
            }
        });
        getContentPane().add(alternativa5RadioButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 660, 30, 30));

        buttonGroup1.add(alternativa3RadioButton);
        alternativa3RadioButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                alternativa3RadioButtonActionPerformed(evt);
            }
        });
        getContentPane().add(alternativa3RadioButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 480, 30, 30));

        buttonGroup1.add(alternativa4RadioButton);
        alternativa4RadioButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                alternativa4RadioButtonActionPerformed(evt);
            }
        });
        getContentPane().add(alternativa4RadioButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 570, 30, 30));

        imageLabel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/Tela AddPerguntas.png"))); // NOI18N
        getContentPane().add(imageLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, -30, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void alternativa2RadioButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_alternativa2RadioButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_alternativa2RadioButtonActionPerformed

    private void alternativa5RadioButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_alternativa5RadioButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_alternativa5RadioButtonActionPerformed

    private void alternativa1RadioButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_alternativa1RadioButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_alternativa1RadioButtonActionPerformed

    private void alternativa3RadioButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_alternativa3RadioButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_alternativa3RadioButtonActionPerformed

    private void alternativa4RadioButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_alternativa4RadioButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_alternativa4RadioButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TelaAdicionarQuestoes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TelaAdicionarQuestoes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TelaAdicionarQuestoes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TelaAdicionarQuestoes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TelaAdicionarQuestoes().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton adicionarQuestaoButton;
    private javax.swing.JRadioButton alternativa1RadioButton;
    private javax.swing.JTextField alternativa1TextField;
    private javax.swing.JRadioButton alternativa2RadioButton;
    private javax.swing.JTextField alternativa2TextField1;
    private javax.swing.JRadioButton alternativa3RadioButton;
    private javax.swing.JTextField alternativa3TextField2;
    private javax.swing.JRadioButton alternativa4RadioButton;
    private javax.swing.JRadioButton alternativa5RadioButton;
    private javax.swing.JTextField alternativa5TextField4;
    private javax.swing.JTextField alterntiva4TextField3;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JLabel imageLabel;
    private javax.swing.JComboBox<String> materiaComboBox;
    private javax.swing.JTextField perguntaTextField5;
    private javax.swing.JButton questaoDificilButton;
    private javax.swing.JButton questaoFacilButton2;
    private javax.swing.JButton questaoMedioButton1;
    private javax.swing.JButton voltarConsultarQuestoesButton;
    // End of variables declaration//GEN-END:variables
}
