/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package br.maua.respondarsepuder.telas;

/**
 *
 * @author Arthur
 */
public class TelaConsultarAluno extends javax.swing.JFrame {

    /**
     * Creates new form TelaAdicionarAluno
     */
    public TelaConsultarAluno() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pesquisarAlunoButton = new javax.swing.JTextField();
        emailAlunoTextField = new javax.swing.JTextField();
        senhaAlunoTextField = new javax.swing.JTextField();
        nomeAlunoTextField = new javax.swing.JTextField();
        voltarConsultarAlunoButton = new javax.swing.JButton();
        removerAlunoButton = new javax.swing.JButton();
        adicionarAlunoButton1 = new javax.swing.JButton();
        atualizarAlunoButton1 = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        consultarAlunosTable = new javax.swing.JTable();
        imageLabel = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        pesquisarAlunoButton.setBackground(new java.awt.Color(242, 92, 84));
        pesquisarAlunoButton.setFont(new java.awt.Font("Arial", 0, 24)); // NOI18N
        pesquisarAlunoButton.setBorder(null);
        pesquisarAlunoButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pesquisarAlunoButtonActionPerformed(evt);
            }
        });
        getContentPane().add(pesquisarAlunoButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(930, 70, 880, 60));

        emailAlunoTextField.setBackground(new java.awt.Color(0, 176, 185));
        emailAlunoTextField.setFont(new java.awt.Font("Arial", 0, 24)); // NOI18N
        emailAlunoTextField.setBorder(null);
        getContentPane().add(emailAlunoTextField, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 390, 320, 60));

        senhaAlunoTextField.setBackground(new java.awt.Color(0, 176, 185));
        senhaAlunoTextField.setFont(new java.awt.Font("Arial", 0, 24)); // NOI18N
        senhaAlunoTextField.setBorder(null);
        senhaAlunoTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                senhaAlunoTextFieldActionPerformed(evt);
            }
        });
        getContentPane().add(senhaAlunoTextField, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 560, 320, 60));

        nomeAlunoTextField.setBackground(new java.awt.Color(0, 176, 185));
        nomeAlunoTextField.setFont(new java.awt.Font("Arial", 0, 24)); // NOI18N
        nomeAlunoTextField.setBorder(null);
        getContentPane().add(nomeAlunoTextField, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 222, 320, 60));

        voltarConsultarAlunoButton.setText("jButton1");
        voltarConsultarAlunoButton.setContentAreaFilled(false);
        voltarConsultarAlunoButton.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        getContentPane().add(voltarConsultarAlunoButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 13, 130, 120));

        removerAlunoButton.setContentAreaFilled(false);
        removerAlunoButton.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        removerAlunoButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                removerAlunoButtonActionPerformed(evt);
            }
        });
        getContentPane().add(removerAlunoButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(800, 870, 370, 100));

        adicionarAlunoButton1.setContentAreaFilled(false);
        adicionarAlunoButton1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        getContentPane().add(adicionarAlunoButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 700, 470, 100));

        atualizarAlunoButton1.setContentAreaFilled(false);
        atualizarAlunoButton1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        atualizarAlunoButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                atualizarAlunoButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(atualizarAlunoButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(1290, 870, 370, 100));

        consultarAlunosTable.setFont(new java.awt.Font("Arial", 0, 24)); // NOI18N
        consultarAlunosTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Nome", "Email", "Senha"
            }
        ));
        jScrollPane1.setViewportView(consultarAlunosTable);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(800, 160, 1050, 680));

        imageLabel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/Tela consultar aluno .png"))); // NOI18N
        getContentPane().add(imageLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, -50, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void removerAlunoButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_removerAlunoButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_removerAlunoButtonActionPerformed

    private void atualizarAlunoButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_atualizarAlunoButton1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_atualizarAlunoButton1ActionPerformed

    private void pesquisarAlunoButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pesquisarAlunoButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_pesquisarAlunoButtonActionPerformed

    private void senhaAlunoTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_senhaAlunoTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_senhaAlunoTextFieldActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TelaConsultarAluno.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TelaConsultarAluno.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TelaConsultarAluno.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TelaConsultarAluno.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TelaConsultarAluno().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton adicionarAlunoButton1;
    private javax.swing.JButton atualizarAlunoButton1;
    private javax.swing.JTable consultarAlunosTable;
    private javax.swing.JTextField emailAlunoTextField;
    private javax.swing.JLabel imageLabel;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField nomeAlunoTextField;
    private javax.swing.JTextField pesquisarAlunoButton;
    private javax.swing.JButton removerAlunoButton;
    private javax.swing.JTextField senhaAlunoTextField;
    private javax.swing.JButton voltarConsultarAlunoButton;
    // End of variables declaration//GEN-END:variables
}
